const levelData = [
    {
        level: 1,
        maxEggs: 1,
        numberOfEnemy: 4,
        numberOfObstacle: 4,
        winningScore: 100,
        distanceScore: 1,
        isFinal: false,
        hatchTimer: 10000,
        enemySpeed: 2,
        numberOfSanctuary: 1,
    },
    {
        level: 2,
        maxEggs: 4,
        numberOfEnemy: 3,
        numberOfObstacle: 3,
        winningScore: 20,
        distanceScore: 5,
        isFinal: false,
        hatchTimer: 1000,
        enemySpeed: 10,
        numberOfSanctuary: 1,
    },
    {
        level: 3,
        maxEggs: 10,
        numberOfEnemy: 4,
        numberOfObstacle: 4,
        winningScore: 30,
        distanceScore: 8,
        isFinal: false,
        hatchTimer: 1000,
        enemySpeed: 2,
        numberOfSanctuary: 1,
    },
    {
        level: 4,
        maxEggs: 15,
        numberOfEnemy: 6,
        numberOfObstacle: 6,
        winningScore: 40,
        distanceScore: 10,
        isFinal: false,
        hatchTimer: 1000,
        enemySpeed: 2,
        numberOfSanctuary: 1,
    },
    {
        level: 5,
        maxEggs: 18,
        numberOfEnemy: 8,
        numberOfObstacle: 5,
        winningScore: 100,
        distanceScore: 20,
        isFinal: false,
        hatchTimer: 1000,
        enemySpeed: 2,
        numberOfSanctuary: 1,
    },
    {
        level: 6,
        maxEggs: 20,
        numberOfEnemy: 10,
        numberOfObstacle: 4,
        winningScore: 100,
        distanceScore: 20,
        isFinal: true,
        hatchTimer: 1000,
        enemySpeed: 2,
        numberOfSanctuary: 1,
    },
];
export default levelData;
